const defaultTerms = {
    en: (date, place, purpose) => [
        `The rent shall be paid on or before the 5th of every month. A late fee may be charged for delayed payments.`,
        `The agreement period starts from ${date} for the ${place}.`,
        `The tenant shall pay electricity and other utility charges promptly. Proof of payment must be shown upon request.`,
        `Either party can terminate this agreement with 1-month prior notice, provided the initial lock-in period is completed.`,
        `The security deposit is refundable only after the tenant hands over the keys and clears all pending dues and utility bills.`,
        `At the time of vacating, painting and professional cleaning charges will be automatically deducted from the security deposit.`,
        `The tenant is responsible for any damages to the rented premises or fixtures beyond normal wear and tear.`,
        `No structural changes, major alterations, or extra wiring shall be done without the owner's written consent.`,
        `Sub-letting or sharing the premises with unauthorized persons is strictly prohibited.`,
        `The owner or agent may inspect the premises with reasonable prior notice.`,
        `The premises shall be used only for ${purpose} purposes and must not be used for any illegal activities or to cause a nuisance to neighbors.`,
        `The tenant must ensure all taps, electrical fittings, and equipment are maintained in working order.`
    ],
    tn: (date, place, purpose) => [
        `ஒவ்வொரு மாதமும் 5-ஆம் தேதிக்குள் வாடகை செலுத்தப்பட வேண்டும். காலதாமதத்திற்கு அபராதக் கட்டணம் வசூலிக்கப்படும்.`,
        `${date} முதல் இந்த ${place} ஒப்பந்தம் நடைமுறைக்கு வருகிறது.`,
        `மின்சாரம் மற்றும் இதர பயன்பாட்டுக் கட்டணங்களை வாடகைதாரர் உரிய நேரத்தில் செலுத்த வேண்டும்.`,
        `எந்தவொரு தரப்பினரும் 1 மாத முன்னறிவிப்புடன் இந்த ஒப்பந்தத்தை முடித்துக்கொள்ளலாம் (ஆரம்பக்கால கட்டாயக் காலம் முடிந்த பிறகு).`,
        `அனைத்து நிலுவைத் தொகைகள் மற்றும் பயன்பாட்டுக் கட்டணங்களைச் சரிபார்த்து, சாவியை ஒப்படைத்த பிறகே முன்பணம் திருப்பி அளிக்கப்படும்.`,
        `காலி செய்யும் போது, பெயிண்டிங் மற்றும் வீட்டை சுத்தம் செய்வதற்கான கட்டணங்கள் முன்பணத்திலிருந்து கழிக்கப்படும்.`,
        `சாதாரண தேய்மானத்தைத் தவிர்த்து கட்டிடத்திற்கோ அல்லது இதர பொருட்களுக்கோ ஏற்படும் சேதங்களுக்கு வாடகைதாரரே முழு பொறுப்பு.`,
        `உரிமையாளரின் எழுத்துப்பூர்வ அனுமதியின்றி கட்டிடத்தில் மாற்றங்கள் செய்யவோ அல்லது கூடுதல் மின் இணைப்புகள் வழங்கவோ கூடாது.`,
        `இந்த இடத்தை வேறு யாருக்கும் உள்வாடகைக்கு விடவோ அல்லது அனுமதி இல்லாத நபர்களை தங்க வைக்கவோ கூடாது.`,
        `உரிமையாளர் தகுந்த முன்னறிவிப்புடன் குடியிருப்பை ஆய்வு செய்ய உரிமை உண்டு.`,
        `இந்த இடம் ${purpose} நோக்கத்திற்காக மட்டுமே பயன்படுத்தப்பட வேண்டும்; சட்டவிரோத செயல்களுக்கோ அல்லது அண்டை வீட்டாருக்கு இடையூறு விளைவிக்கும் செயல்களுக்கோ பயன்படுத்தக்கூடாது.`,
        `குழாய்கள், மின்சாதனங்கள் மற்றும் இதர அமைப்புகளை வாடகைதாரர் நல்ல முறையில் பராமரிக்க வேண்டும்.`
    ]
};
const LEXICON = {
    "form-title": { en: "Agreement Manager", tn: "ஒப்பந்த மேலாளர்" },
    "sec-setup": { en: "Agreement Details", tn: "ஒப்பந்த விபரங்கள்" },
    "lbl-type": { en: "Type", tn: "வகை" },
    "opt-house": { en: "House Rent", tn: "வீட்டு வாடகை" },
    "opt-shop": { en: "Shop Rent", tn: "கடை வாடகை" },
    "lbl-house-num": { en: "House Number", tn: "வீட்டு எண்" },
    "lbl-shop-info": { en: "Shop Name & No", tn: "கடை பெயர் மற்றும் எண்" },
    "lbl-agreement-date": { en: "Agreement Date", tn: "ஒப்பந்த தேதி" },
    "lbl-start-date": { en: "Rent Start Date", tn: "வாடகை தொடங்கும் தேதி" },
    "lbl-owner-sec": { en: "Owner Details", tn: "உரிமையாளர் விபரங்கள்" },
    "lbl-owner-sign": { en: "Owner Signature", tn: "உரிமையாளர் கையொப்பம்" },
    "btn-clear-owner": { en: "CLEAR", tn: "அழிக்க" },
    "lbl-tenant-sec": { en: "Tenant Details", tn: "வாடகைதாரர் விபரங்கள்" },
    "lbl-family": { en: "Authorized Co-occupants", tn: "கூடுதல் குடியிருப்பாளர்கள்" },
    "btn-add-member": { en: "+ Add Member", tn: "+ உறுப்பினர் சேர்" },
    "lbl-tenant-sign": { en: "Tenant Signature", tn: "வாடகைதாரர் கையொப்பம்" },
    "btn-clear-tenant": { en: "CLEAR", tn: "அழிக்க" },
    "lbl-rent-sec": { en: "Charges", tn: "கட்டணங்கள்" },
    "lbl-rent": { en: "Monthly Rent", tn: "மாத வாடகை" },
    "lbl-deposit": { en: "Deposit", tn: "முன்பணம்" },
    "lbl-eb-rate": { en: "EB Rate", tn: "EB யூனிட் கட்டணம்" },
    "lbl-water-charge": { en: "Water", tn: "தண்ணீர் கட்டணம்" },
    "lbl-maintenance": { en: "Maintenance", tn: "பராமரிப்பு" },
    "lbl-total-pay": { en: "Total Monthly Fixed", tn: "மொத்த மாத கட்டணம்" },
    "sec-terms": { en: "Legal Terms & Conditions", tn: "நிபந்தனைகள்" },
    "lbl-terms-edit": { en: "Edit Clauses (One per line)", tn: "நிபந்தனைகளைத் திருத்தவும்" },
    "lbl-inventory": { en: "Inventory List (Fans, Bulbs, Remote, etc)", tn: "பொருட்கள் பட்டியல்" },
    "lbl-btn-reset": { en: "Reset", tn: "மீட்டமை" },
    "lbl-btn-update": { en: "Update", tn: "புதுப்பி" },
    "lbl-btn-print": { en: "Print", tn: "அச்சிடுக" },
    "out-rec-title": { en: "ADVANCE PAYMENT RECEIPT", tn: "முன்பண ரசீது" },
    "out-rec-sig": { en: "Landlord Signature", tn: "உரிமையாளர் கையொப்பம்" },
    "out-lbl-start-date": { en: "START DATE", tn: "தொடங்கும் தேதி" },
    "out-lbl-owner": { en: "OWNER:", tn: "உரிமையாளர்:" },
    "out-lbl-owner-addr": { en: "ADDRESS:", tn: "முகவரி:" },
    "out-lbl-owner-aadhaar": { en: "AADHAAR:", tn: "ஆதார்:" },
    "out-lbl-owner-phone": { en: "PHONE:", tn: "தொலைபேசி:" },
    "out-lbl-tenant": { en: "TENANT:", tn: "வாடகைதாரர்:" },
    "out-lbl-tenant-addr": { en: "ADDRESS:", tn: "முகவரி:" },
    "out-lbl-tenant-aadhaar": { en: "AADHAAR:", tn: "ஆதார்:" },
    "out-lbl-tenant-phone": { en: "PHONE:", tn: "தொலைபேசி:" },
    "out-lbl-monthly-rent": { en: "Monthly Rent:", tn: "மாத வாடகை:" },
    "out-lbl-security-deposit": { en: "Deposit:", tn: "முன்பணம்:" },
    "out-lbl-interest-free": { en: "(Interest-free)", tn: "(வட்டி இல்லா)" },
    "out-lbl-electricity-charge": { en: "EB Rate:", tn: "மின்சாரக் கட்டணம்:" },
    "out-lbl-per-unit": { en: "Unit", tn: "யூனிட்" },
    "out-lbl-water-charge": { en: "Water:", tn: "தண்ணீர்:" },
    "out-lbl-maintenance": { en: "Maintenance:", tn: "பராமரிப்பு:" },
    "out-lbl-total-fixed-monthly": { en: "Total Fixed:", tn: "மொத்தத் தொகை:" },
    "out-lbl-purpose": { en: "RENTAL PURPOSE:", tn: "வாடகை நோக்கம்:" },
    "val-residential": { en: "HOUSE (RESIDENTIAL)", tn: "வீடு (குடியிருப்பு)" },
    "val-shop": { en: "SHOP (COMMERCIAL)", tn: "கடை (வணிகம்)" },
    "out-lbl-owner-sign-print": { en: "OWNER SIGN", tn: "உரிமையாளர் கையொப்பம்" },
    "out-lbl-tenant-sign-print": { en: "TENANT SIGN", tn: "வாடகைதாரர் கையொப்பம்" },
    "out-lbl-witnesses": { en: "WITNESSES:", tn: "சாட்சிகள்:" },
    "in-witness1": { en: "Witness 1 Name & ID", tn: "சாட்சி 1 பெயர் மற்றும் ID" },
    "in-witness2": { en: "Witness 2 Name & ID", tn: "சாட்சி 2 பெயர் மற்றும் ID" },
    "out-lbl-rec-date": { en: "Date:", tn: "தேதி:" },
    "out-lbl-date": { en: "Date:", tn: "தேதி:" },
    "out-sec1": { en: "1. PARTIES", tn: "1. தரப்பினர்" },
    "out-sec2": { en: "2. RENT LOCATION", tn: "2. வாடகை இடத்தின் விபரம்" },
    "out-sec3": { en: "3. RENT & DEPOSITS", tn: "3. கட்டண விபரம்" },
    "out-sec4": { en: "4. TERMS", tn: "4. நிபந்தனைகள்" },
    "out-sec5": { en: "5. INVENTORY", tn: "5. பொருட்கள்" },
    "out-lbl-description": { en: "DESCRIPTION", tn: "விபரம்" },
    "out-lbl-amount": { en: "AMOUNT", tn: "தொகை" },
    "house-rental-agreement": { en: "HOUSE RENTAL AGREEMENT", tn: "வீட்டு வாடகை ஒப்பந்தம்" },
    "shop-rental-agreement": { en: "SHOP RENTAL AGREEMENT", tn: "கடை வாடகை ஒப்பந்தம்" },
    "house-number": { en: "HOUSE NO / ADDRESS", tn: "வீட்டு எண் / முகவரி" },
    "shop-info": { en: "SHOP NAME / ADDRESS", tn: "கடை பெயர் / முகவரி" },
    "agreement-made-on": { en: "Agreement Execution Date", tn: "ஒப்பந்தம் செய்யப்படும் நாள்" },
    "authorized-co-occupants": { en: "CO-OCCUPANTS", tn: "குடியிருப்பாளர்கள்" },
    "lbl-premises-situated": { en: "Rent Location:", tn: "வாடகை இடம்:" }
};
